# Build a Docker image
# https://docs.microsoft.com/vsts/pipelines/languages/docker

queue: 'Hosted Linux Preview'
variables:
  imageName: '$(Build.Repository.Name):$(Build.BuildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .

- task: Maven@2
  inputs:
    mavenPomFile: 'pom.xml'
    jdkVersionOption: 1.8
    jdkArchitectureOption: x64
    checkStyleRunAnalysis: true
    findBugsRunAnalysis: true

# For information on extending this YAML to:
# - Correctly tag your image
# - Push the image to Docker Hub or Azure Container Registry
# - Build and test your app prior to creating the Docker image
# See https://docs.microsoft.com/vsts/pipelines/languages/docker
